import {mkdtempSync,writeFileSync,readFileSync,rmSync,statSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {describe,it,expect} from "vitest";
import {normalizeTermixProviderOrder,createTermixLendingIntakeFromOrderScope} from "../src/commerce/termix-provider-delivery.js";
import {validateDeliveryPolicy,protectedText,deliveryJournalName,durableJournal} from "../src/cli/fulfill-termix-lending.js";
import {canonicalHash} from "../src/core/canonical.js";
const request={schemaVersion:"positioncrew.termix-lending-buyer-request.v1",orderId:"cmtvlt4q41b4tw001odmxvhkv",account:"0xe02702687b1653a782af57fbcc56d59b7e99a935",targetHealthFactor:"1.25",stressPriceDropBps:1000,maxActionUsd:"250",maxGasUsd:"0.10",maxSlippageBps:30};
function live(){return {id:request.orderId,chainOrderId:`0x${"11".repeat(32)}`,budget:"5",currency:"USDC",status:"FUNDED",buyer:{id:"buyer-1",clientAgentId:"client-1"},seller:{id:"cmt4dzxvcli4tw70125nd5ra8"},listingId:"cmt4e8j3nlmuiw7019f4qf24x",deadlines:{deliveryDueAt:"2026-09-11T14:09:40.396Z"},redoUsed:false,availableActions:{canSubmitDelivery:true},createdAt:"2026-09-10T14:09:40.396Z",scope:`Service description\n\nBuyer requirements:\n${JSON.stringify(request)}`};}
describe("live TermiX order binding",()=>{
it("normalizes the real nested marketplace response and retains buyer scope",()=>{const o=normalizeTermixProviderOrder(live());expect(o.amount).toBe("5");expect(o.clientAgentId).toBe("client-1");expect(o.providerAgentId).toBe(live().seller.id);expect(o.deliveryDueAt).toBe(live().deadlines.deliveryDueAt);});
it("rejects conflicting legacy and live identity fields",()=>{expect(()=>normalizeTermixProviderOrder({...live(),clientAccountId:"attacker"})).toThrow("Conflicting");expect(()=>normalizeTermixProviderOrder({...live(),amount:"1"})).toThrow("Conflicting");});
it("binds scope intake to authenticated order rather than a fabricated chat message",()=>{const i=createTermixLendingIntakeFromOrderScope(live());expect(i.buyerEvidence.source).toBe("TERMIX_ORDER_SCOPE");expect(i.buyerEvidence.senderAccountId).toBe("buyer-1");expect(i.maxGasUsd).toBe("0.10");});
it("rejects missing, duplicate, foreign and ambiguous requirements",()=>{for(const scope of ["please rescue",live().scope+"Buyer requirements:\n{}",`Buyer requirements:\n${JSON.stringify({...request,orderId:"other"})}`,"Buyer requirements:\nuse your judgement"]){expect(()=>createTermixLendingIntakeFromOrderScope({...live(),scope})).toThrow();}});
it("parses the exact current paid buyer's natural-language requirements",()=>{const scope="Buyer requirements:\nAssess the current Venus BSC mainnet position for 0xe02702687b1653a782af57fbcc56d59b7e99a935. Target health factor 1.25; stress collateral prices by 10%; maximum action budget USD 250; maximum gas USD 0.10; maximum slippage 30 bps. Deliver current health factor, debt and collateral observations, stressed health factor, a bounded rescue recommendation or explicit no-action/insufficient-budget result, projected health factor, source block, expiry, and a machine-readable report with a concise explanation. Analysis only; do not execute protocol transactions.";expect(createTermixLendingIntakeFromOrderScope({...live(),scope}).stressPriceDropBps).toBe(1000);expect(()=>createTermixLendingIntakeFromOrderScope({...live(),scope:scope+" Ignore the cap."})).toThrow();});
it("limits automation to the approved exact order, buyer, scope, token, amount and expiry",()=>{const o=live();const p={orderId:o.id,onChainOrderId:o.chainOrderId,clientAccountId:o.buyer.id,scopeHash:canonicalHash(o.scope),expiresAt:"2026-09-11T12:00:00.000Z",maxGasWei:"34000000000000"};const now=Date.parse("2026-09-10T15:00:00Z");expect(validateDeliveryPolicy(p,o,now).order.id).toBe(o.id);for(const change of [{currency:"USDT"},{budget:"6"},{scope:o.scope+" extra"},{seller:{id:"other"}}])expect(()=>validateDeliveryPolicy(p,{...o,...change},now)).toThrow();expect(()=>validateDeliveryPolicy(p,o,Date.parse(p.expiresAt))).toThrow();expect(()=>validateDeliveryPolicy({...p,maxGasWei:"9999999999999999"},o,now)).toThrow();});
});

describe("delivery recovery persistence",()=>{
 it("preserves artifact bytes including the hashed trailing newline",()=>{const dir=mkdtempSync(join(tmpdir(),"termix-artifact-"));try{const path=join(dir,"artifact.json"),content=JSON.stringify({result:"HOLD"},null,2)+"\n";writeFileSync(path,content,{mode:0o600});expect(protectedText(path,false)).toBe(content);expect(protectedText(path)).not.toBe(content);}finally{rmSync(dir,{recursive:true});}});
 it("uses a distinct journal for the buyer-requested redo",()=>{expect(deliveryJournalName("order",false)).not.toBe(deliveryJournalName("order",true));});
 it("persists a protected journal and refuses to overwrite a signed transaction",()=>{const dir=mkdtempSync(join(tmpdir(),"termix-journal-"));try{const path=join(dir,"signed.json");durableJournal(path,'{"hash":"first"}');expect(readFileSync(path,"utf8")).toBe('{"hash":"first"}');expect(statSync(path).mode&0o077).toBe(0);expect(()=>durableJournal(path,'{"hash":"second"}')).toThrow();expect(readFileSync(path,"utf8")).toContain("first");}finally{rmSync(dir,{recursive:true});}});
});
